# Generated by Django 3.1 on 2020-09-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_pocketwatch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pocketwatch',
            name='date',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
