# Generated by Django 3.1 on 2020-09-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20200909_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenttype',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
