# Generated by Django 3.1 on 2020-09-15 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_appointmenttype_friendly_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Watch Models',
            },
        ),
        migrations.CreateModel(
            name='WatchType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Watch Types',
            },
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='model',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='type',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='appointment',
            name='watch_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.watchmodel'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='watch_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.watchtype'),
        ),
    ]
