# Generated by Django 3.1 on 2020-09-08 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_appointmenttype_pocketwatches'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PocketWatches',
            new_name='PocketWatch',
        ),
        migrations.AlterModelOptions(
            name='appointmenttype',
            options={},
        ),
    ]
