# Generated by Django 3.1 on 2020-09-09 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200908_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pocketwatch',
            name='appointment',
        ),
        migrations.DeleteModel(
            name='AppointmentType',
        ),
        migrations.DeleteModel(
            name='PocketWatch',
        ),
    ]
